## Competing Risks


```{r packages,include=F}
library(survival)
library(foreign)
library(ggplot2)
library(survminer)
library(rms)
library(flexsurv)
library(dplyr)
library(ciTools)
library(here)
library(visreg)
library(cmprsk)
loyalty=read.csv("Q:\\My Drive\\Fall 3 2016 Survival Analysis\\Data\\Data_R\\loyalty.csv",header=T)
recid=read.csv("Q:\\My Drive\\Fall 3 2016 Survival Analysis\\Data\\Data_R\\recid.csv",header=T)
recid_long=read.csv("Q:\\My Drive\\Fall 3 2016 Survival Analysis\\Data\\Data_R\\recid_long.csv",header=T)
recid_lag=read.csv("Q:\\My Drive\\Fall 3 2016 Survival Analysis\\Data\\Data_R\\recid_lag.csv",header=T)
leaders = read.csv(file = "Q:\\My Drive\\Fall 3 2016 Survival Analysis\\Data\\Data_R\\leaders.csv", header = TRUE)
bladder = read.csv(file = "Q:\\My Drive\\Fall 3 2016 Survival Analysis\\Data\\Data_R\\bladder.csv", header = TRUE)
simple=data.frame(matrix(c(7,8,10,3,2,3,1,1,0,1,1,0),ncol=2))
colnames(simple)=c("tenure","censored")

```


The following code illustrates how to do a competing risk model.

```{r Competing Risks}
leaders$lost = factor(leaders$lost, 0:3, labels = c("In-Office", "Constitutional", "Natural", "Non-Constitutional"))

# Cumulative Incidence Functions #
  cif.dat=leaders[leaders$lost!="In-Office",]  
  cif.tenure=cif.dat$years
  cif.status=cif.dat$lost

  cif.leaders=cuminc(cif.tenure,cif.status,rho=0)
  ggcompetingrisks(cif.leaders)
# Cox Regression Competing Risks #
 tenure=leaders$years
 View(leaders)
 status.leaders=leaders$lost
 x=leaders[,3:12]
 x$africa=ifelse(leaders$region==1,1,0)
 x$asia=ifelse(leaders$region==2,1,0)
 x$latin=ifelse(leaders$region==3,1,0)
 
 gray.natural=crr(tenure,status.leaders,x,failcode="Natural")
 summary(gray.natural)

 gray.const=crr(tenure,status.leaders,x,failcode="Constitutional")
 summary(gray.const)

 gray.nonconst=crr(tenure,status.leaders,x,failcode="Non-Constitutional")
 summary(gray.nonconst)

```

## Repeated Events

```{r Repeated Events}

# Independence Model (Andersen-Gill approach)
bladder.td <- coxph(Surv(start, stop, event == 1) ~ rx + number + size , data = bladder)
summary(bladder.td)

# Independence Model - Marginal means 
bladder.rse <- coxph(Surv(start, stop, event == 1) ~ rx + number + size + cluster(id), data = bladder)
summary(bladder.rse)

# Conditional Model - Assuming Variable Effects Same Across Strata - PWP model
bladder.con <- coxph(Surv(start, stop, event == 1) ~ rx + number + size + strata(enum)+cluster(id), data = bladder)
summary(bladder.con)

# Conditional Model - Assuming Variable Effects change Across Strata - PWP model
bladder.con <- coxph(Surv(start, stop, event == 1) ~ strata(enum)*rx + strata(enum)*number + strata(enum)*size + cluster(id), data = bladder)
summary(bladder.con)


# Gap Time Model - Assuming Variable Effects Same Across Strata #
# Can easily extend the gap time model to assume variable effects different same as above. #
bladder.gap <- coxph(Surv(time = (stop - start), event == 1) ~ rx + number + size + strata(enum) +cluster(id), data = bladder)
summary(bladder.gap)

```

